name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.1'
    
    - name: Build for AMD64
      run: GOOS=linux GOARCH=amd64 go build -o bin/system-monitor-amd64.exec cmd/system-monitor/main.go
    
    - name: Build for ARM64
      run: GOOS=linux GOARCH=arm64 go build -o bin/system-monitor-arm64.exec cmd/system-monitor/main.go
    
    - name: Test
      run: sudo go test ./test/integration/main_test.go
      
    - name: Generate release version
      id: release_version
      run: |
        echo "VERSION=$(date +'%Y.%m.%d-%H%M')" >> $GITHUB_OUTPUT
      
    - name: Create Release
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: release-${{ steps.release_version.outputs.VERSION }}
        name: Release ${{ steps.release_version.outputs.VERSION }}
        draft: false
        prerelease: false
        files: |
          bin/system-monitor-amd64.exec
          bin/system-monitor-arm64.exec
          install.sh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
